# Generated by Django 4.2.5 on 2023-10-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('profession', models.CharField(max_length=256)),
                ('profession2', models.CharField(max_length=256)),
                ('Phone_Number', models.IntegerField()),
                ('email', models.CharField(max_length=256)),
            ],
        ),
    ]
